### PR TITLE
First try

### PR DESCRIPTION
**Pull request by viruxe**
Related to #10 
Needs testing. Some strings might be too big.
CBA to figure out how to include another language in the dropdown.

### CODE REVIEW

**Comment by BigETI** [comment]
You should have used `en-GB` as template, because a significant amount of keys are missing. To fix this, you have to manually put all entries with the missing keys seen in `en-GB` into `pt-PT`.

**Comment by viruxe** [comment]
I'll just redo it with the enGB base when I get back home.

**Comment by viruxe** [comment]
@BigETI how can I make my language appear in the dropdown?

**Comment by BigETI** [comment]
Just modify https://github.com/BigETI/SAMPLauncherNET/blob/master/SAMPLauncherNET/TranslatorInterface.cs#L17 only for testing purposes. However don't stage this file.

**Comment by viruxe** [comment]
It's not entirely complete but covers all the main stuff.

**Comment by BigETI** [comment]
Just tell me when it is ready to merge with `master`.

**Comment by BigETI** [comment]
I'll just merge this for now.

**Pull request merged**
