### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by ziggi**

### CODE REVIEW

**Comment by BigETI** [comment]
Thank you ziggi for translating it in Russian.
I'll look into that later, because I have to be sure that it fits into the UI.
And "Russian" is called "Russisch" in German. It would be great, if you could just change that. :)

**Comment by ziggi** [comment]
Ok, done.

**Comment by BigETI** [comment]
This is when I revert API list entries in Russian mode:
http://bigeti.de/samp/images/russian-launcher-text-missing.png

**Comment by ziggi** [comment]
Done.
image

**Pull request merged**
